name: Code Quality

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]
  schedule:
    # Run weekly on Sundays at 02:00 UTC
    - cron: "0 2 * * 0"

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run lint with detailed output
        run: ./gradlew lint

      - name: Run detekt (if configured)
        run: |
          if grep -q "detekt" app/build.gradle.kts; then
            ./gradlew detekt
          else
            echo "Detekt not configured, skipping..."
          fi
        continue-on-error: true

      - name: Check for security vulnerabilities
        run: |
          # Check for common security issues in Android manifests
          echo "Checking AndroidManifest.xml for security issues..."
          if [ -f app/src/main/AndroidManifest.xml ]; then
            # Check for exportable activities without proper intent filters
            if grep -q 'android:exported="true"' app/src/main/AndroidManifest.xml; then
              echo "⚠️  Found exported components - please review for security implications"
            fi
            
            # Check for debug flags in release
            if grep -q 'android:debuggable="true"' app/src/main/AndroidManifest.xml; then
              echo "❌ Debug flag found in manifest - should be false for release"
              exit 1
            fi
            
            # Check for network security config
            if ! grep -q 'android:networkSecurityConfig' app/src/main/AndroidManifest.xml; then
              echo "ℹ️  Consider adding network security config for better HTTPS enforcement"
            fi
          fi

      - name: Upload lint results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lint-results-detailed
          path: |
            app/build/reports/lint-results*.html
            app/build/reports/lint-results*.xml

      - name: Comment PR with lint results
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request' && always()
        with:
          script: |
            const fs = require('fs');
            const path = 'app/build/reports/lint-results-debug.xml';

            if (fs.existsSync(path)) {
              const lintResults = fs.readFileSync(path, 'utf8');
              const issues = (lintResults.match(/<issue/g) || []).length;
              
              const comment = `## 🔍 Lint Results
              
              Found ${issues} lint issues in this PR.
              
              📋 Download the detailed lint report from the workflow artifacts to review all issues.
              
              ${issues > 0 ? '⚠️ Please address lint issues before merging.' : '✅ No lint issues found!'}`;
              
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment
              });
            }
